# Site settings
title: paul.buser.website
email: paul@buser.website
description: > # this means to ignore newlines until "baseurl:"
  I like discussing ideas and noticing what I see around me.
  Sometimes I write about these observations.
  I'm interested in how technology can offer new ways of thinking about and approaching the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paul.buser.website" # the base hostname & protocol for your site
twitter_username: pcbuser
github_username:  p-buse

# Build settings
markdown: kramdown
encoding: utf-8
